paginate: 10

name: Seccubus
description: Easy Automated vulnerability scanning and reporting
url: https://www.seccubus.com
baseurl: 
timezone: Europe/Amsterdam

permalink: pretty
paginate_path: "news/:num/"
highlighter: true
markdown: redcarpet
redcarpet:
    extensions:
        - no_intra_emphasis
        - autolink
        - strikethrough
        - fenced_code_blocks
