paginate: 10

name: Seccubus
description: Easy Automated vulnerability scanning and reporting
url: /Seccubus_v2/
timezone: Europe/Amsterdam

permalink: pretty
paginate_path: "news/:num/"
highlighter: true
markdown: redcarpet
redcarpet:
    extensions:
        - no_intra_emphasis
        - autolink
        - strikethrough
        - fenced_code_blocks
