paginate: 10

permalink: pretty
paginate_path: "news/:num/"
highlighter: true
markdown: redcarpet
redcarpet:
    extensions:
        - no_intra_emphasis
        - autolink
        - strikethrough
        - fenced_code_blocks
