version: 2
jobs:
  unshallow:
    docker:
      - image: circleci/ubuntu-server:latest

    steps:
      - checkout
      - run: if [ -e .git/shallow ]; then git fetch --unshallow; fi

  build:
    docker:
      - image: circleci/ubuntu-server:latest

    steps:
      - checkout
      - run: prove

workflows:

  version: 2

  buildall:
    jobs:
      - checkout
      - build
