version: 2
jobs:
  deps:
    docker:
      - image: perl:latest

    steps:
      - checkout
      - run: if [ -e .git/shallow ]; then git fetch --unshallow; fi

  prove:
    docker:
      - image: perl:latest

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install cpanminus build-essential
      - run: cpanm --installdeps --notest .
      - run: mysql -e "create database seccubus"
      - run: prove

workflows:

  version: 2

  buildall:
    jobs:
      - prove
