version: 2
jobs:

  unit_tests:
    docker:
      - image: perl:latest
        environment:
        - PERL5LIB: "."
        - MYSQL_HOME: "/root/project/.circleci"
      - image: circleci/mysql:latest
    parallelism: 3

    steps:
      - checkout
      - run:
          name: Install prerequisite packages
          command: apt-get update; apt-get -y install build-essential zip dnsutils bsdmainutils mysql-client
      - restore_cache:
          key: cpanm-{{ .Branch }}-{{ checksum "Makefile.PL" }}
      - run: cpanm --notest REHSACK/List-MoreUtils-XS-0.425_001.tar.gz
      - run: cpanm --installdeps --notest .
      - save_cache:
          key: cpanm-{{ .Branch }}-{{ checksum "Makefile.PL" }}
          paths:
            - "/usr/local/lib/perl5/site_perl"
      - run:
          name: Wait for database
          command: |
            while ! echo -n > /dev/tcp/127.0.0.1/3306; do
              sleep 1
              echo -n .
            done
      - run:
          name: Create database(s)
          command: |
            mysql -e "create database seccubus"
            mysql -e "create database seccubus_create"
            mysql -e "create database seccubus_upgrade"
      - run:
          name: Unit test
          command: circleci tests glob t/* | circleci tests split --split-by=timings --timings-type=filename | xargs -n 1 prove

  build:
    docker:
      - image: perl:latest
        environment:
        - PERL5LIB: "."

    steps:
      - checkout
      - run:
          name: Install prerequisite packages
          command: apt-get update; apt-get -y install build-essential zip dnsutils bsdmainutils mysql-client default-jre
      - restore_cache:
          key: cpanm-{{ .Branch }}-{{ checksum "Makefile.PL" }}
      - run:
          name: Build
          command: ./build_all
      - store_artifacts:
          path: /root/project/build/Seccubus*.tar.gz

  build_deb:
    docker:
      - image: debian:9
        environment:
        - PERL5LIB: "."

    steps:
      - checkout
      - run:
          name: Install prerequisite packages
          command: apt-get update; apt-get -y install build-essential debhelper default-jre git
      - run:
          name: Build
          command: deb/makedeb.sh
      - save_cache:
          key: deb-{{ .Branch }}
          paths:
            - "/root/project/build"
      - store_artifacts:
          path: /root/project/build

  check_deb_debian7:
    docker:
      - image: debian:7

    steps:
      - run: apt-get update; apt-get install -y ca-certificates
      - restore_cache:
          key: deb-{{ .Branch }}
      - run:
          name: Install package (shoud fail)
          shell: bash -ex
          command: if dpkg -i /root/project/build/*.deb; then echo "NOT ok"; exit 99; else echo "OK" ; fi
      - run: debconf-set-selections <<< 'mysql-server mysql-server/root_password password your_password'
      - run: debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password your_password'
      - run:
          name: Install failed packages (shoud work)
          command: apt-get -y install mysql-serverapt-get install -f -y
      - run:
          name: Seccubus should be running on port 8443
          command: echo -n >/dev/tcp/localhost/8443

  check_deb_debian8:
    docker:
      - image: debian:8

    steps:
      - run: apt-get update; apt-get install -y ca-certificates
      - restore_cache:
          key: deb-{{ .Branch }}
      - run: debconf-set-selections <<< 'mysql-server mysql-server/root_password password your_password'
      - run: debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password your_password'
      - run:
          name: Install package (shoud fail)
          shell: bash -ex
          command: apt-get -y install mysql-serverapt-get install -f -y
      - run:
          name: Install failed packages (shoud work)
          command: apt-get install -f -y
      - run:
          name: Seccubus should be running on port 8443
          command: echo -n >/dev/tcp/localhost/8443

  check_deb_debian9:
    docker:
      - image: debian:9

    steps:
      - run: apt-get update; apt-get install -y ca-certificates
      - restore_cache:
          key: deb-{{ .Branch }}
      - run:
          name: Install package (shoud fail)
          shell: bash -ex
          command: if dpkg -i /root/project/build/*.deb; then echo "NOT ok"; exit 99; else echo "OK" ; fi
      - run:
          name: Install failed packages (shoud work)
          command: apt-get install -f -y
      - run:
          name: Seccubus should be running on port 8443
          command: echo -n >/dev/tcp/localhost/8443

  check_deb_kali:
    docker:
      - image: kalilinux/kali-linux-docker:latest

    steps:
      - run: apt-get update; apt-get install -y ca-certificates
      - restore_cache:
          key: deb-{{ .Branch }}
      - run:
          name: Install package (shoud fail)
          shell: bash -ex
          command: if dpkg -i /root/project/build/*.deb; then echo "NOT ok"; exit 99; else echo "OK" ; fi
      - run:
          name: Install failed packages (shoud work)
          command: apt-get install -f -y
      - run:
          name: Seccubus should be running on port 8443
          command: echo -n >/dev/tcp/localhost/8443


workflows:

  version: 2

  unit_and_integration_tests:
    jobs:
      - unit_tests
      - build:
          requires:
            - unit_tests

  debian_package_building:
    jobs:
      - build_deb
      - check_deb_debian9:
          requires:
            - build_deb
      - check_deb_debian8:
          requires:
            - build_deb
      - check_deb_debian7:
          requires:
            - build_deb
      - check_deb_kali:
          requires:
            - build_deb
