version: 2
jobs:

  test:
    docker:
      - image: jekyll/jekyll:latest
    steps:
      - run:
          name: Install prerequisites
          command: |
            apk --no-progress update ;
            apk --no-progress git
      - checkout
      - run: jekyll build
      - run: jekyll hyde

workflows:
  version: 2
  build_and_test:
    jobs:
      - test