version: 2
jobs:
  debs:
    docker:
      - image: perl:latest
        environment:
          PERL5LIB: "."

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install build-essential
      - restore_cache:
          key: cpanm-{{ .Branch }}-{{ checksum "Makefile.PL" }}
      - run: cpanm --installdeps --notest .
      - save_cache:
          key: cpanm-{{ .Branch }}-{{ checksum "Makefile.PL" }}
          paths:
            - "/usr/local/lib/perl5/site_perl"

  tests_0:
    docker:
      - image: perl:latest
        environment:
          PERL5LIB: "."


    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install build-essential
      - restore_cache:
          key: cpanm-{{ .Branch }}-{{ checksum "Makefile.PL" }}
      - run: cpanm --installdeps --notest .
      - save_cache:
          key: cpanm-{{ .Branch }}-{{ checksum "Makefile.PL" }}
          paths:
            - "/usr/local/lib/perl5/site_perl"
      - run: if [ -e .git/shallow ]; then git fetch --unshallow; fi
      - run: prove t/0*

workflows:

  version: 2

  buildall:
    jobs:
      - debs
      - tests_0:
          requires:
            - debs
