version: 2
jobs:
  deps:
    docker:
      - image: circleci/ubuntu-server:latest

    steps:
      - checkout
      - run: if [ -e .git/shallow ]; then git fetch --unshallow; fi

  prove:
    docker:
      - image: circleci/ubuntu-server:latest

    steps:
      - checkout
      - run: apt-get install cpanminus
      - run: cpanm --installdeps --notest .
      - run: mysql -e "create database seccubus"
      - run: prove

workflows:

  version: 2

  buildall:
    jobs:
      - prove
